### PR TITLE
chore: Revert storybook adder back to @latest when v8.2.0 releases

### PR DESCRIPTION
**Pull request by manuel3108**
Relates #386 

- Revert "add `--legacy-peer-deps` flag for npm installs"
- chore: Revert storybook adder back to @latest when v8.2.0 releases

### CODE REVIEW

**Comment by benmccann** [comment]
Ah, I guess this doesn't work yet because it doesn't have the other fix that's in 8.2.0. But 8.2.0 should be released in the next week anyway, so I guess we can just wait a bit. Thanks for checking!

**Comment by benmccann** [comment]
Storybook 8.2 is finally out! The latest is currently 8.2.1: https://www.npmjs.com/package/storybook

**Comment by manuel3108** [comment]
They also fixed https://github.com/storybookjs/storybook/issues/28474 and https://github.com/storybookjs/storybook/issues/28475 which were happening on the latest 8.2 beta build.

But they managed to re-introduce https://github.com/storybookjs/storybook/issues/27096, which again disappears when using `next` ([`8.3.0-alpha.0`](https://www.npmjs.com/package/storybook/v/8.3.0-alpha.0)). They must have moved some commits around. 

Should we release this with the beta again, or should we report this issue again and wait for it to be resolved?

**Comment by manuel3108** [comment]
Just had a look locally, and 8.2.5 is still not working as it should. The currently published implementation is broken, so let's use the next version to make it much better already. 

Let's leave the original issue open though, to provide further tracking.

**Pull request merged**
