### PR TITLE
chore: update adder descriptions

### PR DESCRIPTION
**Pull request by benmccann**
Updating the descriptions with details the differentiate between the options and help you choose. Like "The modern CSS framework that just works" is something that I imagine any CSS framework would say about themselves and I've honestly got no idea what "Headless" means in the context of an ORM.

### CODE REVIEW

**Comment by manuel3108** [comment]
> is something that I imagine any CSS framework would say about themselves

Yeah, that's because that's where those texts came from, from their respective websites.

Not sure about the retention thing. Is this really something the user will use to differentiate the tools? But I understand that at least `bootstrap` and `bulma` would be the same without that.

**Comment by benmccann** [comment]
I do look at those surveys when choosing tools and is one of the things that helped encourage me to use Svelte. But I recognize there are a lot of inputs to choose tools and this is only one source. Though their ranking does correlate quite highly with what I've heard from other maintainers/ambassadors. I think it would be helpful to have some way to indicate to novice users that we wouldn't necessarily recommend Bootstrap for a new project. But right now it's in the first position, which makes it seem favored.

Screenshot from 2024-06-21 13-20-32

**Comment by AdrianGonz97** [comment]
I do agree with @manuel3108 that including the retention stats does feel a bit off

we could just express our recommendations by altering the list's order and then, instead of using descriptions, maybe we could link back to their respective docs pages (or maybe even a future svelte/svelte-add site pages that gives more detailed descriptions)? 

something like this:
img

alternatively, since we now control `@svelte-add/clack-prompts`, we could slightly alter the colors to reflect the most used packages as well:
img

or:
img
(it doesn't have to be green, but just for demoing purposes)

**Comment by manuel3108** [comment]
(ordering of those adders is still on my list)

**Comment by benmccann** [comment]
I removed the retention info, but I actually like @AdrianGonz97's idea of just putting a link to the site or docs, so perhaps I should remove the descriptions? Or do you want to keep them for now for the website?

**Comment by AdrianGonz97** [comment]
> perhaps I should remove the descriptions? Or do you want to keep them for now for the website?

i think we can keep the descriptions and just change what's displayed in the prompt inside of `@svelte-add/core`  here:
https://github.com/svelte-add/svelte-add/blob/18080e5fb9c7240da70b100b46936ce0e81733c8/packages/core/adder/execute.ts#L221

**Comment by benmccann** [comment]
thanks for the feedback! closing in favor of https://github.com/svelte-add/svelte-add/pull/435

**Pull request closed without merging**
