### PR TITLE
chore: use vitest

### PR DESCRIPTION
**Pull request by manuel3108**
Relates / in preparation for #461 

Command to test adders locally will slightly change with this:
```
pnpm test tailwindcss
```

will now be
```
pnpm test -t tailwindcss
```

You can also use `pnpm test:ui` which will also spin up vitest ui, although the ui is pretty barebones and does not allow running filtered tests in example.

Currently a draft, as I needed to switch from `pnpm` to `npm` for the testing in order to make everything work. Now trying to figure out what causes the problem

### CODE REVIEW

**Comment by manuel3108** [comment]
For whatever reason this works in CI.....

**Comment by benmccann** [comment]
I believe @dominikg setup the tests for `create-svelte` and handled whatever pnpm magic was needed there to make things work, so perhaps he'd be able to lend some advice on this one

**Comment by manuel3108** [comment]
As soon as I switch this line from using `npm` to `pnpm` 26 out of 51 one tests start failing on windows:
https://github.com/svelte-add/svelte-add/blob/0bd41a87989daa52e7123ee0cca46de1928d7631/packages/testing-library/utils/workspace.ts#L18

I tried to reproduce the error in a codespace, but everything seems to work there, as in CI (well expect for the storybook tests, but I'm not interested in these atm). Also tried a to do a fresh clone on my machine, but I only got the same error as before.

**Comment by dominikg** [comment]
> I believe @dominikg setup the tests for `create-svelte` and handled whatever pnpm magic was needed there to make things work, so perhaps he'd be able to lend some advice on this one

tests for create-svelte are special as you have to prevent the local monorepo packages from bleeding in. so they generate a separate monorepo root in a temp dir. its weird and pretty specific to create-svelte.

a similar pattern could be used for svelte-add but not sure you need it unless you want e2e-tests that validate the adder worked by installing and building the e2e project again. but I'd be fine with snapshots validating expected file changes

**Comment by manuel3108** [comment]
Closing in favor of #544

**Pull request closed without merging**
