### PR TITLE
Added bun support

### PR DESCRIPTION
**Pull request by ThatXliner**

### CODE REVIEW

**Comment by manuel3108** [comment]
Hey @ThatXliner
were you able to test this? Windows does not want to install WSL correctly.
From the other source code, it look like there might be other places that might need to be adjusted to make this work.

**Comment by RubenPX** [comment]
@manuel3108 @ThatXliner 

 It's not required to use WSL anymore. [Bun is compatible with windows now](https://bun.sh/blog/bun-v1.1)

To install bun in windows, go to https://bun.sh ant it seays how to install it with powershell

**Comment by manuel3108** [comment]
@RubenPX Thanks for your help in identifying this. 

`svelte-add` will be deprecated pretty soon, so it doesn't make sense to implement the changes here. I have already opened an issue in it's successor project `svelte-compose`

**Comment by Electroid** [comment]
@manuel3108 Understand this package will soon be deprecated. It would be great to sneak #333 in before you do that, given that `svelte-add` is used in many places and will still be depended on for a while.

**Comment by ThatXliner** [comment]
In that case, I will close my PR

**Pull request closed without merging**
